language: cpp
matrix:
  include:
#    - os: osx
#      compiler: clang
#      install: "brew update && brew cask install osxfuse"
#      sudo: required
#      script: "cmake . && make -j4 && ./securefs v && ctest -V"
    - os: linux
      dist: trusty
      sudo: required
      install: "sudo apt-get update && sudo apt-get install -y cmake fuse libfuse-dev"
      script: "cmake . && make -j4 && ./securefs v && ctest -V"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: eFi2vlF7A6r5FKMpa4wjFIgdaLu8v5tOh9FzWjetHafBnYW47bsWnqo6L0PmuJ6jkXkcnA/4DVE1Spdw0fLE2XLvOGJemwohz4Xe9UTrlNtsBW0rPxUYRoglEYyK0VNVHOBzs+ZlWv9gN4APOZPVaEobT0DN6rBNDd4/KiLmUr4a7wReZJSoNE5rGTerHnnUuUnMCeRzdtkadMp2YJWCC0HbaZ/bRi2FYX5DvLHTl0/PU26Cj9OkL49XbDZ0xC/UORvj2TrhDu+frl4iceiUc7ol1R9dqxMruhr8lQLhFFO2d1MHCojDR7c/CLtpRDaaCjmnTNsf5JeWcsTIUHIeqmlxCHeQyLRyMFjQl+9Gp4Ed3oqVB+cNn1FbEr+HW3+R7mEqVQUfIccIZYBQ4TPpL9OfwwWr4GRJRejAylTlH1OlL1oUugpapUYdtRJOquuvnBDJjfugmTVeo+U4rp+H1S06mK5RtTkS3F5RU0i4Xtok1NHBat0Mn21RQCDo4qhe89L2jLx8b/0lgH2JMwWW4BHJ0ePm5blGayN3mKJqzBqcQ2XMaXZ1uo3zHYht40I2SAUKmf/JqBlfBMLv3zk4tcwoJdzoF60YmwFNQ5wHq7cFF429k/3w1XA4gkbceCgoCaE7zMWxC/hE6Snp9hMN7OT9YYwM8OUyAs6OyPEmLUI=
  file_glob: true
  file:
    - "securefs"
  on:
    tags: false
